services:
  ollama2:
    image: ollama/ollama:0.3.4
    ports:
      - ${OLLAMA_EXPOSED:-19290}:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    tty: true
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]

volumes:
  ollama_data:
    driver: local
